language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
before_install:
  - python --version
  - pip install -U pip
  - pip install poetry
install:
  - poetry install -v
script:
  - pytest